/**
 * API Route Stubs for GameForge
 *
 * Auto-generated by Claudery Blueprint Generator
 *
 * Copy these to your app/api/ directory and customize as needed.
 * Each function represents a separate route handler.
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// ============================================
// AUTH ROUTES
// ============================================

/**
 * POST /api/auth/signin
 */
export async function POST_SIGNIN(request: NextRequest) {
  const supabase = await createClient();
  const { email, password } = await request.json();

  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error) {
    return NextResponse.json({ error: { code: "AUTH_ERROR", message: error.message } }, { status: 401 });
  }

  return NextResponse.json({ data: { user: data.user } });
}

/**
 * POST /api/auth/signup
 */
export async function POST_SIGNUP(request: NextRequest) {
  const supabase = await createClient();
  const { email, password } = await request.json();

  const { data, error } = await supabase.auth.signUp({
    email,
    password,
  });

  if (error) {
    return NextResponse.json({ error: { code: "AUTH_ERROR", message: error.message } }, { status: 400 });
  }

  return NextResponse.json({ data: { user: data.user } }, { status: 201 });
}

/**
 * POST /api/auth/signout
 */
export async function POST_SIGNOUT() {
  const supabase = await createClient();
  await supabase.auth.signOut();
  return NextResponse.json({ success: true });
}

/**
 * GET /api/auth/me
 */
export async function GET_ME() {
  const supabase = await createClient();
  const { data: { user }, error } = await supabase.auth.getUser();

  if (error || !user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  return NextResponse.json({ data: { user } });
}


// ============================================
// GAME ROUTES
// ============================================

/**
 * GET /api/games
 * List all games for current user
 */
export async function GET_GAMES(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const limit = parseInt(searchParams.get("limit") || "20");
  const offset = parseInt(searchParams.get("offset") || "0");

  const { data, error, count } = await supabase
    .from("games")
    .select("*", { count: "exact" })
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({
    data,
    pagination: { total: count || 0, limit, offset, hasMore: (count || 0) > offset + limit },
  });
}

/**
 * POST /api/games
 * Create new game
 */
export async function POST_GAMES(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();
  // TODO: Add zod validation

  const { data, error } = await supabase
    .from("games")
    .insert({ ...body, user_id: user.id })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data }, { status: 201 });
}

/**
 * GET /api/games/[id]
 * Get single game by ID
 */
export async function GET_GAME_BY_ID(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { data, error } = await supabase
    .from("games")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", user.id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: { code: "NOT_FOUND" } }, { status: 404 });
  }

  return NextResponse.json({ data });
}

/**
 * PUT /api/games/[id]
 * Update game
 */
export async function PUT_GAME(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();

  const { data, error } = await supabase
    .from("games")
    .update(body)
    .eq("id", params.id)
    .eq("user_id", user.id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data });
}

/**
 * DELETE /api/games/[id]
 * Delete game
 */
export async function DELETE_GAME(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { error } = await supabase
    .from("games")
    .delete()
    .eq("id", params.id)
    .eq("user_id", user.id);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}

// ============================================
// USER ROUTES
// ============================================

/**
 * GET /api/users
 * List all users for current user
 */
export async function GET_USERS(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const limit = parseInt(searchParams.get("limit") || "20");
  const offset = parseInt(searchParams.get("offset") || "0");

  const { data, error, count } = await supabase
    .from("users")
    .select("*", { count: "exact" })
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({
    data,
    pagination: { total: count || 0, limit, offset, hasMore: (count || 0) > offset + limit },
  });
}

/**
 * POST /api/users
 * Create new user
 */
export async function POST_USERS(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();
  // TODO: Add zod validation

  const { data, error } = await supabase
    .from("users")
    .insert({ ...body, user_id: user.id })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data }, { status: 201 });
}

/**
 * GET /api/users/[id]
 * Get single user by ID
 */
export async function GET_USER_BY_ID(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { data, error } = await supabase
    .from("users")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", user.id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: { code: "NOT_FOUND" } }, { status: 404 });
  }

  return NextResponse.json({ data });
}

/**
 * PUT /api/users/[id]
 * Update user
 */
export async function PUT_USER(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();

  const { data, error } = await supabase
    .from("users")
    .update(body)
    .eq("id", params.id)
    .eq("user_id", user.id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data });
}

/**
 * DELETE /api/users/[id]
 * Delete user
 */
export async function DELETE_USER(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { error } = await supabase
    .from("users")
    .delete()
    .eq("id", params.id)
    .eq("user_id", user.id);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}

// ============================================
// HELPER: Create actual route files
// ============================================

/*
To use these stubs, create route files like:

app/api/items/route.ts:
-----------------------
import { GET_ITEMS, POST_ITEMS } from "@/lib/api-stubs";
export { GET_ITEMS as GET, POST_ITEMS as POST };

app/api/items/[id]/route.ts:
---------------------------
import { GET_ITEM_BY_ID, PUT_ITEM, DELETE_ITEM } from "@/lib/api-stubs";
export { GET_ITEM_BY_ID as GET, PUT_ITEM as PUT, DELETE_ITEM as DELETE };
*/
